[tool.poetry]
name = "template"
version = "0.1.0"
description = ""
authors = ["hoge <foo@bar...>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
flake8 = "*"
isort = "*"
mypy = "*"
pre-commit = "*"
pydocstyle = "*"
pytest = "*"
black = { version="*", allow-prereleases = true }

[tool.black]
line-length = 100
target-version = ["py39"]
exclude = '''
(
  \.eggs
  | \.git
  | \.mypy_cache
  | \.pytest_cache
  | dist
)
'''

[tool.isort]
include_trailing_comma = true
line_length = 100
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
